### ISSUE TITLE
Python 3 support/cutover

### ISSUE THREAD

**Issue by yesrod** [yesrod/hoplite#7]
In theory Hoplite should still run with Python3 from the work done for v1.0.6 but I haven't tested it yet.

Since Python 2 is EOL I should make Hoplite Python3 only.

**Comment by adorsey-NOAA** [comment]
Also recommend upgrading to Raspbian Buster (or running Python 3.6+ via some other method) as Python 3.5 in Stretch is EOL

**Comment by yesrod** [comment]
Also recommend at least Raspbian Buster (or other means of running Python 3.6) as Python 3.5 is EOL and many dependencies are complaining.

**Comment by yesrod** [comment]
Still runs under Python 3, but reported numbers are way off.  I've made a silly math mistake somewhere.

**Comment by yesrod** [comment]
"Done" in v1.2.0
